import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigationHeader from "@/components/header/MainNavigationHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavigationHeader />
        {children}
      </body>
    </html>
  );
}
